### ISSUE TITLE
Achieve same design

### ISSUE THREAD

**Issue by amitkhairnar44** [huextrat/TheGorgeousLogin#1]
You can achieve 100% design by using Stack widget.
Overlap that login form with the button.

**Comment by huextrat** [comment]
Hi, yes I did it at the beginning with a Positioned button but the button is not clickable over the login card ...

**Comment by amitkhairnar44** [comment]
Well i just cloned your repository and did some changes 
Guess what it's working, the button is clickable
![screenshot_20180914-122914](https://user-images.githubusercontent.com/18245511/45534801-ede98f00-b819-11e8-814a-819ec66bd182.png)

**Comment by kalismeras61** [comment]
@amitkhairnar44  can you share your code ?

**Comment by huextrat** [comment]
@amitkhairnar44 Well gj, can you create a request to update the code pls ;) I had an issue over the white card to click the button but if you found a solution this design is perfect

**Comment by amitkhairnar44** [comment]
@kalismeras61 Sure i'll
@huextrat Okay

**Comment by huextrat** [comment]
Thanks @amitkhairnar44

**Comment by amitkhairnar44** [comment]
Fixed in #2

**Comment by huextrat** [comment]
It allowed me to add a box shadow 😍 @amitkhairnar44

**Comment by amitkhairnar44** [comment]
> It allowed me to add a box shadow 😍 @amitkhairnar44

Cool
