### ISSUE TITLE
Undefined_getter

### ISSUE THREAD

**Issue by VinitPanchal96** [huextrat/TheGorgeousLogin#10]
First thing first, thanks for sharing this beautiful UI with flutter. As I'm a new in flutter, I really don't know how to build login and signup using flutter but you made my work a lot easier.

**Problem:** There is a error in the login_page.dart file that says 

The getter 'Colors' isn't defined for the class 'Theme'.
Try importing the library that defines 'Colors', correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.dart(undefined_getter)

Could you tell me how to solve that? 

I also want to know that How can I intrigate this UI with firebase in order to store USER's confidential data like email and password.

**Comment by huextrat** [comment]
Thanks for the feedback. Can you provide more information about the crash please.

About the firebase part, just called firebase_auth when the button login is clicked by passing the email & password.

**Comment by VinitPanchal96** [comment]
I think the problem is in my own project files bcuz maybe i copy paste some code but when I open your whole project in emulator it worked perfectly. Once again thanks a lot for solving my doubt and about firebase.
