### ISSUE TITLE
Exception occur when sliding between the forms

### ISSUE THREAD

**Issue by mshahrokhi** [huextrat/TheGorgeousLogin#17]
Hi...
after running the app, if you click on text fields and sliding between the forms an exception will occur...

`flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: RRect argument contained a NaN value.
flutter: 'dart:ui/painting.dart':
flutter: Failed assertion: line 37: '<optimized out>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   TextField
flutter:   file:///Users/mohammad/Documents/Flutter/TheGorgeousLogin-master/lib/ui/login_page.dart:230:32
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _rrectIsValid (dart:ui/painting.dart:37:10)
flutter: #3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
flutter: #4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2042:14)
flutter: #5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
flutter: #6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
flutter: #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #13     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
flutter: #14     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4861:13)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #32     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #34     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
flutter: #35     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
flutter: #36     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
flutter: #37     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:438:19)
flutter: #38     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
flutter: #39     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #40     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #41     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #46     _invoke (dart:ui/hooks.dart:251:10)
flutter: #47     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderEditable#4f484 relayoutBoundary=up15:
flutter:   creator: _Editable-[GlobalKey#ef5f4] ← Semantics ← CompositedTransformTarget ←
flutter:     IgnorePointer-[GlobalKey#75551] ← Semantics ← _PointerListener ← Listener ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#0ab20] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← Scrollable ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=212.0, 0.0<=h<=Infinity)
flutter:   size: Size(212.0, 19.0)
flutter:   cursorColor: Color(0x102196f3)
flutter:   showCursor: ValueNotifier<bool>#c954a(true)
flutter:   maxLines: 1
flutter:   minLines: null
flutter:   selectionColor: Color(0xff90caf9)
flutter:   textScaleFactor: 1.0
flutter:   locale: en_US
flutter:   selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream,
flutter:     isDirectional: false)
flutter:   offset: ScrollPositionWithSingleContext#d558e(offset: 0.0, range: 0.0..0.0, viewport: 212.0,
flutter:     ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#5757c,
flutter:     ScrollDirection.idle)
flutter: This RenderObject had the following child:
flutter:     text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════`

Thanks

**Comment by huextrat** [comment]
A major update is available the error should be solved
