### ISSUE TITLE
fit the screen 

### ISSUE THREAD

**Issue by bturkoglu** [huextrat/TheGorgeousLogin#8]
I have tried the iPhone X,XR e fits exactly,
but the design doesn't fit exactly to devices like iphone SE, iphone 7, nexus 5. (need scroll down)
How can I change the code so that each size fits on the screen?

**Comment by sjha2048** [comment]
hey @bahaTRKGLU! you can try https://pub.dev/packages/flutter_screenutil this plugin to achieve your goal.
